### ISSUE TITLE
[Bug] Support Minecraft version is error

### ISSUE THREAD

**Issue by 8MiYile** [ExoPlant/NoMoreScore#1]
On modrinth, the mod displays the following information

![image](https://user-images.githubusercontent.com/25455400/212489735-7346529c-ffd6-4cbb-8aae-7a8401d0977d.png)

---

But under this file `fabric.mod.json` 

```json
{
  "depends": {
      "minecraft":"1.17.1"
  }
}
```
https://github.com/Ecorous/NoMoreScore/blob/main/src/main/resources/fabric.mod.json#L31

---

Related information: Crash-Report from Quilt（About remove this tag）
[Before](https://mclo.gs/9bDRSzE) and [After](https://mclo.gs/KmXdEqM)

---

I just want to say: `Are you kidding me?`

**Comment by Ecorous** [comment]
The "After" link is a multiconnect error, but I will fix the fabric.mod.json and reupload later today

**Comment by Ecorous** [comment]
I forgot, am fixing now

**Comment by Ecorous** [comment]
I'll push out a new release now.

**Comment by Ecorous** [comment]
Okay, for some reason, twitch won't let me log in to curse, so I'll try to upload to curse another time. I'll leave this open in the meantime. Modrinth is uploaded already

**Comment by 8MiYile** [comment]
Not have automatic build?

**Comment by Ecorous** [comment]
> Not have automatic build?

Do you mean github actions artifacts, or cf/mr auto uploading? I haven't gotten round to either. I can do it at some point though

**Comment by Ecorous** [comment]
I only just got round to updating curse, sorry. It's fixed now
